spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      
server:
  servlet:
    context-path: /mwpl-analyser
      
ta:
  mwpl:
    nse:
      combined_vol_and_oi:
        url: https://www.nseindia.com/archives/nsccl/mwpl/combineoi_
        localFilePath: /Users/dhanagarajan/mwpl/
        urlDateFormat: ddMMyyyy
        dbDateFormat: dd-MMM-yyyy
