spring:
  profiles:    
    active:
    - prod
  data:
    mongodb:
      database: trading-data

server:
  servlet:
    context-path: /mwpl-analyser
   
ta:
  mwpl:
    nse:
      combined_vol_and_oi:
        url: https://www.nseindia.com/archives/nsccl/mwpl/combineoi_      
        urlDateFormat: ddMMyyyy
