spring:
  data:
    mongodb:
      uri: mongodb+srv://mwpl-admin:mwpl@cluster0-xbdej.gcp.mongodb.net/trading-data?retryWrites=true&w=majority

ta:
  mwpl:
    nse:
      combined_vol_and_oi:
        localFilePath: /tradeapp/downloadedFiles