spring:
  profiles:    
    active:
    - prod
  data:
    mongodb:
      database: trading-data

server:
  servlet:
    context-path: /mwpl-analyser
   
ta:
  mwpl:
    nse:
      combined_vol_and_oi:
        url: https://www.nseindia.com/archives/nsccl/mwpl/combineoi_      
        urlDateFormat: ddMMyyyy
        dbDateFormat: dd-MMM-yyyy
        percentageDiff: 6.0
      quote_url: https://www.nseindia.com/live_market/dynaContent/live_watch/get_quote/GetQuote.jsp?
  notifications:
    fromEmail: noreply@danistradeapp.com
    toEmail: dnagarajan89@gmail.com
    mwpl:
      datastored:
        templateId: d-9a2767fc6e044ed9b5237c8137446ee4
        emailSubject: Mwpl data saved for {{processedDate}}
        emailContent: Mwpl data saved for {{processedDate}}.
      nodata:
        emailSubject: No mwpl data found for {{attemptedDate}}
        emailContent: No mwpl data found for {{attemptedDate}}.
sendgrid:
    apiKey: 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

