spring:
  profiles:    
    active:
    - prod 

server:
  servlet:
    context-path: /mwpl-analyser
    
ta:
  mwpl:
    nse:
      combined_vol_and_oi:
        url: https://www.nseindia.com/archives/nsccl/mwpl/combineoi_      
        urlDateFormat: ddMMyyyy
        dbDateFormat: dd-MMM-yyyy
